#!/bin/bash

#ll HTML files in the current directory

html_files=$(find . -type f -name "*.html")



# For each HTML file

for file in $html_files; do

  # Get the filename without the path

  filename="${file##*/}"

  

  # Construct the path of the file in the parent directory

  parent_file="../$filename"



  # Check if the file does not exist in the parent directory or is newer

  if [ ! -e "$parent_file" ] || [ "$file" -nt "$parent_file" ]; then
    # Copy the file to the parent directory
    cp "$file" "../"
  fi
done
